### ISSUE TITLE
how can i use cssFontsPath?

### ISSUE THREAD

**Issue by ovi1337** [jeerbl/webfonts-loader#4]
Hi,
now i'm trying many hours to use cssFontsPath to modify the fonts path inside of the generated template and i don't get it work.
Otherwise, is there any way to fetch the file-hash of the font-file inside of the template to getting it work manually?

something like:
```hbs
    @font-face {
        font-family: "{{fontName}}";
        src: url('../fonts/{{fontName}}.eot?{{hash}}');
        src: url('../fonts/{{fontName}}.eot#iefix?{{hash}}') format('eot'),
        url('../fonts/{{fontName}}.woff2?{{hash}}') format('woff2'),
        url('../fonts/{{fontName}}.woff?{{hash}}') format('woff'),
        url('../fonts/{{fontName}}.ttf?{{hash}}') format('truetype'),
        url('../fonts/{{fontName}}.svg#{{fontName}}?{{hash}}') format('svg');
    }
```

or can i attach an anonymous callback function to the src attribute, to generate my own?

I would be happy for some hints of you. Thank you in advance! :)

**Comment by jeerbl** [comment]
Hi

I fixed the issue in the @next (0.2.4) release.
Try installing it with `npm install --save webfonts-loader@next` and tell me if it is working on your side.

Thx
Jerome

**Comment by ovi1337** [comment]
The problem is still existing, i believe that the `cssFontsPath` attribute is generally not working. Can you please check, if you can set a custom base-path for the font files?

I've tried it to set this value on many places, but it's generally not work. Could be that i still make something wrong.

```js
module.exports = {
    fontName: 'glyphicons',
    files: ['./custom/**/*.svg'],
    cssTemplate: './templates/icons.scss.hbs',
    cssFontsPath: '../newcustompath/',
    baseSelector: 'glyphicon',
    classPrefix: 'glyphicon-',
    fixedWidth: true,
    normalize: true,
    fontHeight: 1001,
    types: [
        'eot',
        'svg',
        'ttf',
        'woff',
        'woff2'
    ],
    formatOptions: {
      	ttf: {
      		ts: 0
      	}
    },
    templateOptions: {
        cssFontsPath: '../newcustompath/',
    }
};
```

```js
module: {
            rules: [{
                enforce: 'pre',
                test: /\.font\.(js|json)$/,
                loader: font.extract({
                    loader: [
                        {
                            loader: 'raw-loader',
                        },
                        {
                            loader: 'webfonts-loader',
                            options: {
                                fileName: './fonts/[fontname].[ext]?[hash]',
                                cssFontsPath: '../newcustompath/',
                                templateOptions: {
                                    cssFontsPath: '../newcustompath/'
                                }
                            }
                        }
                    ]
                })
            }]
        }
```

**Comment by jeerbl** [comment]
I checked and it seems related to the `webfonts-generator`, on which you [opened an issue](https://github.com/sunflowerdeath/webfonts-generator/issues/19) by the way. Let's wait for this to be resolved on their side as I can't do much more than forwarding this parameter to their package.

Closing until something comes out from them.

Thx
Jerome

**Comment by jeerbl** [comment]
Duplicate from [webfonts-generator #17](https://github.com/sunflowerdeath/webfonts-generator/issues/19)
